CREATE TABLE neverlostdb_organizations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    description TEXT NOT NULL,
    type TEXT NOT NULL,
    address TEXT,
    website TEXT,
    phone_number TEXT
);