CREATE TABLE neverlostdb_animals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    species TEXT NOT NULL,
    breed TEXT,
    color TEXT,
    age INTEGER,
    gender TEXT,
    description TEXT,
    is_lost BOOLEAN NOT NULL,
    in_shelter INTEGER REFERENCES neverlostdb_organizations(id)
);