CREATE TABLE neverlostdb_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    animal_id INTEGER REFERENCES neverlostdb_animals(id),
    org_id INTEGER REFERENCES neverlostdb_organizations(id),
    date_time_of_last_post TIMESTAMPTZ,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);