CREATE TABLE neverlostdb_topics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    event_id INTEGER REFERENCES neverlostdb_events(id),
    date_time_of_last_post TIMESTAMPTZ,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);