CREATE TABLE neverlostdb_posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    topic_id INTEGER REFERENCES neverlostdb_topics(id),
    event_id INTEGER REFERENCES neverlostdb_events(id),
    date_modified TIMESTAMPTZ,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);